//
// UserAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class UserAPI: APIBase {
    /**
     ユーザ一覧
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getUsers(completion: @escaping ((_ data: [InlineResponse200]?,_ error: Error?) -> Void)) {
        getUsersWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     ユーザ一覧
     - GET /user
     - examples: [{contentType=application/json, example=[ {
  "lon" : "aeiou",
  "id" : "aeiou",
  "lat" : "aeiou"
} ]}]

     - returns: RequestBuilder<[InlineResponse200]> 
     */
    open class func getUsersWithRequestBuilder() -> RequestBuilder<[InlineResponse200]> {
        let path = "/user"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[InlineResponse200]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
